export interface CubaProvince {
  value: string;
  label: string;
  municipalities: string[];
}

export const cubaProvinces: CubaProvince[] = [
  {
    value: "Pinar del Río",
    label: "Pinar del Río",
    municipalities: [
      "Consolación del Sur",
      "Guane",
      "La Palma",
      "Los Palacios",
      "Mantua",
      "Minas de Matahambre",
      "Pinar del Río",
      "San Juan y Martínez",
      "San Luis",
      "Sandino",
      "Viñales",
    ],
  },
  {
    value: "Artemisa",
    label: "Artemisa",
    municipalities: [
      "Alquízar",
      "Artemisa",
      "Bahía Honda",
      "Bauta",
      "Caimito",
      "Candelaria",
      "Guanajay",
      "Güira de Melena",
      "Mariel",
      "San Antonio de los Baños",
      "San Cristóbal",
    ],
  },
  {
    value: "La Habana",
    label: "La Habana",
    municipalities: [
      "Arroyo Naranjo",
      "Boyeros",
      "Centro Habana",
      "Cerro",
      "Cotorro",
      "Diez de Octubre",
      "Guanabacoa",
      "Habana del Este",
      "Habana Vieja",
      "La Lisa",
      "Marianao",
      "Playa",
      "Plaza de la Revolución",
      "Regla",
      "San Miguel del Padrón",
    ],
  },
  {
    value: "Mayabeque",
    label: "Mayabeque",
    municipalities: [
      "Batabanó",
      "Bejucal",
      "Güines",
      "Jaruco",
      "Madruga",
      "Melena del Sur",
      "Nueva Paz",
      "Quivicán",
      "San José de las Lajas",
      "San Nicolás",
      "Santa Cruz del Norte",
    ],
  },
  {
    value: "Matanzas",
    label: "Matanzas",
    municipalities: [
      "Calimete",
      "Cárdenas",
      "Ciénaga de Zapata",
      "Colón",
      "Jagüey Grande",
      "Jovellanos",
      "Limonar",
      "Los Arabos",
      "Martí",
      "Matanzas",
      "Pedro Betancourt",
      "Perico",
      "Unión de Reyes",
    ],
  },
  {
    value: "Cienfuegos",
    label: "Cienfuegos",
    municipalities: [
      "Abreus",
      "Aguada de Pasajeros",
      "Cienfuegos",
      "Cruces",
      "Cumanayagua",
      "Lajas",
      "Palmira",
      "Rodas",
    ],
  },
  {
    value: "Villa Clara",
    label: "Villa Clara",
    municipalities: [
      "Caibarién",
      "Camajuaní",
      "Cifuentes",
      "Corralillo",
      "Encrucijada",
      "Manicaragua",
      "Placetas",
      "Quemado de Güines",
      "Ranchuelo",
      "Remedios",
      "Sagua la Grande",
      "Santa Clara",
      "Santo Domingo",
    ],
  },
  {
    value: "Sancti Spíritus",
    label: "Sancti Spíritus",
    municipalities: [
      "Cabaiguán",
      "Fomento",
      "Jatibonico",
      "La Sierpe",
      "Sancti Spíritus",
      "Taguasco",
      "Trinidad",
      "Yaguajay",
    ],
  },
  {
    value: "Ciego de Ávila",
    label: "Ciego de Ávila",
    municipalities: [
      "Baraguá",
      "Bolivia",
      "Chambas",
      "Ciego de Ávila",
      "Ciro Redondo",
      "Florencia",
      "Majagua",
      "Morón",
      "Primero de Enero",
      "Venezuela",
    ],
  },
  {
    value: "Camagüey",
    label: "Camagüey",
    municipalities: [
      "Camagüey",
      "Carlos Manuel de Céspedes",
      "Esmeralda",
      "Florida",
      "Guáimaro",
      "Jimaguayú",
      "Minas",
      "Najasa",
      "Nuevitas",
      "Santa Cruz del Sur",
      "Sibanicú",
      "Sierra de Cubitas",
      "Vertientes",
    ],
  },
  {
    value: "Las Tunas",
    label: "Las Tunas",
    municipalities: [
      "Amancio",
      "Colombia",
      "Jesús Menéndez",
      "Jobabo",
      "Las Tunas",
      "Majibacoa",
      "Manatí",
      "Puerto Padre",
    ],
  },
  {
    value: "Granma",
    label: "Granma",
    municipalities: [
      "Bartolomé Masó",
      "Bayamo",
      "Buey Arriba",
      "Campechuela",
      "Cauto Cristo",
      "Guisa",
      "Jiguaní",
      "Manzanillo",
      "Media Luna",
      "Niquero",
      "Pilón",
      "Río Cauto",
      "Yara",
    ],
  },
  {
    value: "Holguín",
    label: "Holguín",
    municipalities: [
      "Antilla",
      "Báguanos",
      "Banes",
      "Cacocum",
      "Calixto García",
      "Cueto",
      "Frank País",
      "Gibara",
      "Holguín",
      "Mayarí",
      "Moa",
      "Rafael Freyre",
      "Sagua de Tánamo",
      "Urbano Noris",
    ],
  },
  {
    value: "Santiago de Cuba",
    label: "Santiago de Cuba",
    municipalities: [
      "Contramaestre",
      "Guamá",
      "Mella",
      "Palma Soriano",
      "San Luis",
      "Santiago de Cuba",
      "Segundo Frente",
      "Songo-La Maya",
      "Tercer Frente",
    ],
  },
  {
    value: "Guantánamo",
    label: "Guantánamo",
    municipalities: [
      "Baracoa",
      "Caimanera",
      "El Salvador",
      "Guantánamo",
      "Imías",
      "Maisí",
      "Manuel Tames",
      "Niceto Pérez",
      "San Antonio del Sur",
      "Yateras",
    ],
  },
  {
    value: "Isla de la Juventud",
    label: "Isla de la Juventud",
    municipalities: ["Isla de la Juventud"],
  },
];

export const getMunicipalitiesByProvince = (province: string) => {
  return cubaProvinces.find((item) => item.value === province)?.municipalities ?? [];
};
